# This workflow will public Cocoapods and Docs

name: Release publisher

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}${{ github.ref_name != github.event.repository.default_branch && github.ref || github.run_id }}
  cancel-in-progress: ${{ github.ref_name != github.event.repository.default_branch }}

jobs:
  publish-cocoapods:
    name: 🥜 Publish Cocoapods
    uses: ./.github/workflows/publich_podspec.yml

  publish-docs:
    name: 📝 Publish Docs
    uses: ./.github/workflows/deploy-docs.yml

  publish-app:
    name: 🚀 Publish Test App
    uses: ./.github/workflows/publish-demo-app.yml
