name: Publish Adyen.podspec
on: [workflow_dispatch]
jobs:

  publish:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

    - name: Select latest Xcode
      uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
      with:
        xcode-version: latest-stable

    - name: Publish Adyen.podspec
      run: |
        gem install cocoapods
        pod trunk push Adyen.podspec --allow-warnings
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
