name: 📸 Generate Snapshots
on:
    workflow_dispatch:
          
jobs:
  Generate:
    runs-on: macos-13-xlarge
    
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
    - uses: n1hility/cancel-previous-runs@e709d8e41b16d5d0b8d529d293c5e126c57dc022 # v3.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: 🔨 Select Xcode
      uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
      with:
        xcode-version: '15.1'

    - name: 🧹 Clear existing Snapshots
      run: |
        find ./Tests/SnapshotTests -name "__Snapshots__" -exec rm -rf {} +
    - name: 📸 Generate Snapshots
      run: |
        xcodebuild test -project "${project}" -scheme "${scheme}" ${params} -destination "name=iPhone 15 Pro,OS=17.2" -destination "name=iPad (10th generation),OS=17.2" | xcpretty --utf --color
      env:
        project: 'Adyen.xcodeproj'
        params: '-skipPackagePluginValidation'
        scheme: 'GenerateSnapshots'
        
    - name: 🚀 Create Pull Request
      uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
      with:
        delete-branch: true
        branch: update-snapshots-github-action
        commit-message: "🤖 Generated Snapshots"
        title: "🤖 Generate Snapshots"
        body: "Regenerate snapshots"
        token: ${{ secrets.GITHUB_TOKEN }}
