name: 📚 Library Evolution Compatibility

on:
  pull_request:
    types: [opened, synchronize, reopened]
    
  push:
    branches:
      - develop
      
jobs:

  build:
    name: Verify
    runs-on: macos-13-xl

    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
    - uses: n1hility/cancel-previous-runs@e709d8e41b16d5d0b8d529d293c5e126c57dc022 # v3.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Select latest Xcode
      uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
      with:
        xcode-version: '14.3'

    - name: "xcodebuild clean archive BUILD_LIBRARY_FOR_DISTRIBUTION=YES"
      run: |
        xcodebuild -version
        xcodebuild clean archive -project "${project}" -scheme "${scheme}" ${params} -destination "${destination}" | xcpretty --utf --color && exit ${PIPESTATUS[0]}
      env:
        project: 'Adyen.xcodeproj'
        params: '-archivePath "archives/Adyen-iphoneos.xcarchive" -skipPackagePluginValidation SKIP_INSTALL=NO BUILD_LIBRARY_FOR_DISTRIBUTION=YES'
        scheme: 'Adyen'
        destination: 'generic/platform=iOS'
